name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v4
      - run: ls -la
      - run: npm install
      - run: npm test
      - run: python3 -m pip install semgrep
      - run: semgrep scan
